version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-app
        container_name: cardviewer-app
        ports:
            - "80:80"
        volumes:
            - ./basic:/var/www/html
    